apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: development
data:
  APPLICATION: Application untuk development
  VERSION: 1.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: env-service
  namespace: development
spec:
  type: NodePort
  selector:
    name: nodejs-env
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30046

