apiVersion: v1
kind: Namespace
metadata:
  name: production

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: production
data:
  APPLICATION: Application untuk Production
  VERSION: 1.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: env-service
  namespace: production
spec:
  type: NodePort
  selector:
    name: nodejs-env
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30045

